CREATE DATABASE gymapp;


-- EXERCISE MODEL
-- DONE
CREATE TABLE exercise (
  ExerciseID SERIAL PRIMARY KEY,
  Name VARCHAR(100) NOT NULL UNIQUE,
  MuscleGroup VARCHAR(50) NOT NULL,
  MovementType VARCHAR(50) NOT NULL,
  Video TEXT,
  Description TEXT
);

-- SETSTRUCTURE MODEL
CREATE TABLE setStructure (
  SetID SERIAL PRIMARY KEY,
  Name VARCHAR(255) NOT NULL UNIQUE,
  Reps INTEGER[] NOT NULL
);

-- WORKOUTSTRUCTURE MODEL
CREATE TABLE workoutStructure (
  WorkoutID SERIAL PRIMARY KEY,
  Name VARCHAR(255) NOT NULL UNIQUE,
  Group INTEGER[] NOT NULL, 
  ExerciseIDs INTEGER[] NOT NULL, 
  SetIDs INTEGER[] NOT NULL
);


-- SPLITSTRUCTURE MODEL